# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: htmlzip

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.7
  install:
  	- method: setuptools

sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

conda:
  environment: py3ml.yml
